spring.datasource.url=jdbc:postgresql://localhost:5432/agenda-web
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.configuration.maximum-pool-size=2
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.thymeleaf.cache=false

spring.mvc.hiddenmethod.filter.enabled=true